default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: db
  port: 3306

development:
  <<: *default
  database: productivity_hub_development

test:
  <<: *default
  database: productivity_hub_test

production:
  <<: *default
  database: productivity_hub_production
